locale                   : "en-US"
title                    : "choisaehee123"
title_separator          : "-"
subtitle                 : choisaehee123
name                     : "choisaehee"
description              : "choisaehee123"
url                      : "http://choisaehee123.github.io"
baseurl                  : ""
